### PR TITLE
Upgrade Tutorials to v2.0.0 alpha.8

### PR DESCRIPTION
**Pull request by danforbes**

### CODE REVIEW

**Comment by danforbes** [comment]
I encountered paritytech/subport#16 when upgrading the tutorial to start a private chain. I don't think it's a blocking problem, but I wanted to note it.

**Comment by JoshOrndorff** [comment]
@Swader I believe you were interested in reviewing these PRs too right?

**Review by JoshOrndorff — APPROVED** [review]
Awesome work.

It's a bummer the alpha.8 release has those aura errors, but luckily they don't stop the chain from working. I wonder if it's worth adding a note in the text saying that there is a known issue and linking to https://github.com/paritytech/substrate/issues/6052 ?

**Review by riusricardo — APPROVED** [review]
LGTM :+1:

**Comment by Swader** [comment]
Thanks for the ping @JoshOrndorff, I need these next week so right on time! Will go through each, step by step, make sure it works.

**Pull request merged**
